<?php

declare(strict_types=1);

namespace App\Domains\Identity\Enums;

enum OrganizationPermission: string
{
    case VIEW_ORGANIZATION = 'VIEW_ORGANIZATION';
    case MANAGE_ORGANIZATION = 'MANAGE_ORGANIZATION';
    case VIEW_SETTINGS = 'VIEW_SETTINGS';
    case MANAGE_SETTINGS = 'MANAGE_SETTINGS';
    case MANAGE_MEMBERSHIPS = 'MANAGE_MEMBERSHIPS';
    case VIEW_AUDIT = 'VIEW_AUDIT';
    case VIEW_PATIENTS = 'VIEW_PATIENTS';
    case MANAGE_PATIENTS = 'MANAGE_PATIENTS';
    case REVIEW_PATIENT_MERGES = 'REVIEW_PATIENT_MERGES';
    case VIEW_CONSENTS = 'VIEW_CONSENTS';
    case MANAGE_CONSENTS = 'MANAGE_CONSENTS';
    case BREAK_GLASS_PATIENT_ACCESS = 'BREAK_GLASS_PATIENT_ACCESS';
    case VIEW_SCHEDULE = 'VIEW_SCHEDULE';
    case MANAGE_SCHEDULE = 'MANAGE_SCHEDULE';
    case MANAGE_SCHEDULING_CONFIGURATION = 'MANAGE_SCHEDULING_CONFIGURATION';
    case VIEW_ENCOUNTERS = 'VIEW_ENCOUNTERS';
    case MANAGE_ENCOUNTERS = 'MANAGE_ENCOUNTERS';
}
