<?php

declare(strict_types=1);

namespace App\Domains\Audit\Enums;

enum AuditResourceType: string
{
    case ORGANIZATION = 'ORGANIZATION';
    case FACILITY = 'FACILITY';
    case OPERATIONAL_SETTINGS = 'OPERATIONAL_SETTINGS';
    case ORGANIZATION_MEMBERSHIP = 'ORGANIZATION_MEMBERSHIP';
    case AUDIT_EVENT = 'AUDIT_EVENT';
    case PATIENT = 'PATIENT';
    case PATIENT_MERGE_REVIEW = 'PATIENT_MERGE_REVIEW';
    case PATIENT_CONSENT = 'PATIENT_CONSENT';
    case PRIVACY_DECISION = 'PRIVACY_DECISION';
    case BREAK_GLASS_ACCESS = 'BREAK_GLASS_ACCESS';
    case APPOINTMENT = 'APPOINTMENT';
    case SCHEDULING_RESOURCE = 'SCHEDULING_RESOURCE';
    case APPOINTMENT_TYPE = 'APPOINTMENT_TYPE';
    case WAITLIST_ENTRY = 'WAITLIST_ENTRY';
    case ENCOUNTER = 'ENCOUNTER';
}
